// Migration generated by TronIDE from a recorded deploy flow.
// Review it, then run: tronbox migrate --network <nile|shasta|mainnet>

const ThreeRealmsCards = artifacts.require('ThreeRealmsCards');

module.exports = async function (deployer) {
  await deployer.deploy(ThreeRealmsCards);
  const threeRealmsCards = await ThreeRealmsCards.deployed();

  await threeRealmsCards.mintPeachGardenGenesis("0x5b38da6a701c568545dcfcb03fcb875f56beddc4");

  await threeRealmsCards.mintPeachGardenGenesis("0x5b38da6a701c568545dcfcb03fcb875f56beddc4");
};
